from lns import LNs

if __name__ == '__main__':
    lns1 = LNs()
    lns1.from_list(['v1', 'v2', 'v3', 'v4'])
    print('LNS1')
    lns1.print_()
    lns2 = LNs()
    lns2.from_list(['v5', 'v6'])
    print('LNS2')
    lns2.print_()
    lns3 = LNs()
    lns3.from_list(['v7', 'v8'])
    print('LNS3')
    lns3.print_()
    """lns1.tail_merge(lns2)
    print('lns1 merged with lns2 at tail')
    lns1.print_()
    lns1.extend(lns3)
    lns1.print_()
    lns2.extend(lns3)
    print(lns2.ck_next_node().next.ck_data())
    lns2.print_()
    """
    lns1.tail_merge_with(lns2, lns3)
    print('LNS1 after tail_merge_with(lns2, lns3)')
    lns1.print_()
    print('; and LNS2')
    lns2.print_()
    lns2.visit_all()
    print(lns2.visited())
